source "https://rubygems.org"

ruby "3.2.0"

gem "rails", "~> 7.1.3", ">= 7.1.3.4"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

# Use the Puma web server
gem "puma", ">= 5.0"

gem 'httparty'
gem 'uuidtools'
gem 'rack-cors'

# Use Guard for automatic reloading
gem 'guard'
gem 'guard-rails', require: false

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end

group :test do
  gem 'minitest'
  gem 'minitest-rails'
  gem 'rails-controller-testing'
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'mocha'
end